Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Mireo.RepeatableFields:
            - Main
      inspector:
        dataTypes:
          repeatable:
            typeConverter: Mireo\RepeatableFields\TypeConverter\RepeatableConverter
            editor: Mireo.RepeatableFields/Inspector/Editors/RepeatableFieldEditor
          Mireo\RepeatableFields\Model\Repeatable:
            typeConverter: Mireo\RepeatableFields\TypeConverter\RepeatableToArrayConverter
        editors:
          Mireo.RepeatableFields/Inspector/Editors/RepeatableFieldEditor:
            editorOptions:
              autoFocus: false
              disabled: false
              maxlength: null
              readonly: false
              buttonAddLabel: 'Mireo.RepeatableFields:Main:addRow'
              indexKey: null
              min: 0
              max: 100
              controls:
                move: true
                remove: true
                add: true
                collapse: true
    Ui:
      resources:
        javascript:
          'Mireo.RepeatableFields:RepeatableField':
            resource: 'resource://Mireo.RepeatableFields/Public/Plugin.js'
        stylesheets:
          'Mireo.RepeatableFields:RepeatableField':
            resource: 'resource://Mireo.RepeatableFields/Public/Plugin.css'
